version: "2"

run:
  timeout: 5m
  tests: false

formatters:
  enable:
    - gofmt

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Default: false
    check-type-assertions: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
