---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentruntime.io
  resources:
  - agents
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentruntime.io
  resources:
  - agents/finalizers
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - agentruntime.io
  resources:
  - agents/status
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unagnt.io
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unagnt.io
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - unagnt.io
  resources:
  - workflows/status
  verbs:
  - get
  - patch
  - update
